default: &default
  adapter: mysql2
  encoding: utf8mb4
  host: <%= ENV.fetch("DATABASE_HOST") { 'db' } %>
  username: <%= ENV.fetch("DATABASE_USER") { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

staging:
  <<: *default
  database: app_staging

production:
  <<: *default
  database: app_production
