version: '3'
services:
  db:
    image: postgres:11.5-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web: &app_base
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/app:cached
      - bundle:/user/local/bundle:cached
      # exclude volumes to improve performance
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    ports:
      - "3000:3000"
    depends_on:
      - db
  webpacker:
    <<: *app_base
    command: ./bin/webpack-dev-server
    depends_on:
      - web
    ports:
      - '3035:3035'
volumes:
  bundle:
    driver: local